version: "2"  # required to adjust maintainability checks

checks:
  argument-count:
    config:
      threshold: 5

  method-complexity:
    config:
      threshold: 8

plugins:
  radon:  # Cyclomatic complexity
    enabled: true
    config:
      threshold: "D"  # Reports complexity > 10

  pep8:
    enabled: true
    checks:
      E731:  # Use of lambda
        enabled: false
      E501:  # line length
        enabled: false


  markdownlint:
    enabled: true

  git-legal:
    enabled: true

  fixme:
    enabled: true