# Configuration file for continuous documentation building via Read the Docs
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Set the version of Python and requirements required to build docs
python:
  version: 3.7
  system_packages: true
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .
