language: python

os:
  - linux

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - "pip install -r requirements.txt"
  - "python setup.py install"

script:
  - pytest