language: python

matrix:
  # macOS environment
  - os: osx
    compiler: clang
    osx_image: xcode10.1
    addons:
      homebrew:
        update: true
        packages:
          - eigen

install:
  - pip install -r requirements.txt

script:
  "pytest"

