# Configuration file for continuous integration testing with travis

language: python

os:
  - linux

python:
  - "3.7-dev"

install:
  - pip install -r requirements.txt
  - python setup.py install

  # For running tests
  - pip install pytest
  - pip install "coverage<5.0.0"  # For compatibility with coveralls
  - pip install pytest-cov
  - pip install python-coveralls

script:
  - pytest --cov=analysis/

after_success:
  - coveralls