# Configuration file for continuous integration testing with travis

language: python

os:
  - linux

python:
  - "3.7-dev"

# Install codeclimate API
# https://docs.codeclimate.com/

install:
  - pip install -r requirements.txt
  - python setup.py install

  # Extra dependencies for running tests
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - coverage run -m pytest

after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
